AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template.
################################
# Parameters
################################
Parameters: 
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: <Input Key Pair Name>
    Description: Select keypair name.
################################
# Mappings
################################
Mappings: 
  prd:
    PublicSubnet1a: { ID: <Input Subnet ID>}
    ServerName:
      InstanceType: t2.micro
      AmiId: <Input AMI ID>
      SecurityGroupId: <Input SecurityGroup ID>
      NetworkInterfaceId: <Input ENI ID>
      NetworkInterfaceMgrId: <Input ENI ID>
      IAMRoleArn: <Input IAM Role Name>

Resources:
################################
# EC2Instance
################################
  VM01:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ prd, ServerName, AmiId ]
      InstanceType: !FindInMap [ prd, ServerName, InstanceType ]
      Monitoring: false
      DisableApiTermination: false
      # BlockDeviceMappings: 
      #     - DeviceName: "/dev/sda1"
      #       Ebs: 
      #         VolumeType: gp2
      #         VolumeSize: 30
      NetworkInterfaces:
        - DeleteOnTermination: false
          DeviceIndex: 0
          NetworkInterfaceId: !FindInMap [ prd, ServerName, NetworkInterfaceId ]
      KeyName: !Ref KeyPair
      IamInstanceProfile: !Ref IAMInstanceProfile
      Tags:
        - Key: Name
          Value: ServerName
################################
# NetworkInterface
################################
  NetworkInterfaceAttachment:
    Type: AWS::EC2::NetworkInterfaceAttachment
    Properties:
      DeviceIndex: 1
      InstanceId: !Ref VM01
      NetworkInterfaceId: !FindInMap [ prd, ServerName, NetworkInterfaceMgrId ]
################################
# EBS
################################
  # EC2Volume:
  #   Type: AWS::EC2::Volume
  #   Properties:
  #     AvailabilityZone: ap-northeast-1a
  #     SnapshotId: snap-0fb17b3a864d72e02
  #     VolumeType: gp2
  #     Tags:
  #       - Key: Name
  #         Value: ServerName-C
  # EC2VolumeAttachment:
  #   Type: AWS::EC2::VolumeAttachment
  #   Properties:
  #     Device: /dev/sda1
  #     InstanceId: !Ref VM01
  #     VolumeId: !Ref EC2Volume
################################
# IAM
################################
  IAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: 
        - !FindInMap [ prd, ServerName, IAMRoleArn ]