AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template.
################################
# Parameters
################################
Parameters: 
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select keypair name.
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  DbUserName:
    Type: String
    Description: Input database username.
  DbUserPassword:
    NoEcho: true
    Type: String
    Description: Input database password.
################################
# Mappings
################################
# Mappings: 

Resources:
################################
# VPC
################################
  cfnVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: cfn-vpc
################################
# Subnet
################################
  cfnPublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref cfnVPC
      CidrBlock: 10.0.11.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: cfn-vpc-public-1a
  cfnPublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref cfnVPC
      CidrBlock: 10.0.12.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: cfn-vpc-public-1c
  cfnPrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref cfnVPC
      CidrBlock: 10.0.21.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: cfn-vpc-private-1a
  cfnPrivateSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref cfnVPC
      CidrBlock: 10.0.22.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: cfn-vpc-private-1c
################################
# InternetGateway
################################
  cfnInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: cfn-vpc-igw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref cfnVPC
      InternetGatewayId: !Ref cfnInternetGateway
################################
# PublicRoute
################################
  cfnPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref cfnVPC
      Tags:
        - Key: Name
          Value: cfn-vpc-public-rt
  cfnPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: cfnInternetGateway
    Properties:
      RouteTableId: !Ref cfnPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref cfnInternetGateway
  cfnPublicRouteTableAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref cfnPublicSubnet1a
      RouteTableId: !Ref cfnPublicRouteTable
  cfnPublicRouteTableAssociation1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref cfnPublicSubnet1c
      RouteTableId: !Ref cfnPublicRouteTable
################################
# EC2Instance
################################
  cfnWeb1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref cfnPublicSubnet1a
      Monitoring: false
      DisableApiTermination: false
      BlockDeviceMappings: 
          - DeviceName: "/dev/xvda"
            Ebs: 
              VolumeType: gp2
              VolumeSize: 20
      SecurityGroupIds:
        - !Ref cfnWebSecurityGroup
      KeyName: !Ref KeyPair
      UserData: !Base64 |
        #!/bin/bash -ex
        yum -y update
      Tags:
        - Key: Name
          Value: cfn-web1
################################
# EIP for EC2
################################
  cfnEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref cfnWeb1
################################
# SecurityGroup for EC2
################################
  cfnWebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: cfn-web-sg
      GroupDescription: Managed by CloudFormation
      VpcId: !Ref cfnVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: cfn-web-sg
################################
# SecurityGroup for RDS
################################
  cfnDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: cfn-db-sg
      GroupDescription: Managed by CloudFormation
      VpcId: !Ref cfnVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref cfnWebSecurityGroup
      Tags:
        - Key: Name
          Value: cfn-db-sg
################################
# RDS
################################
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # instance parameters
      DBInstanceIdentifier: dbinstance
      DBInstanceClass: db.t2.micro
      MultiAZ: false
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref rdsDBSubnetGroup
      DBParameterGroupName: !Ref rdsDBParameterGroup
      VPCSecurityGroups:
        - !Ref cfnDBSecurityGroup
      # storage parameters
      StorageType: gp2
      AllocatedStorage: 20
      StorageEncrypted: false
      # engine parameters
      Engine: mysql
      EngineVersion: 5.7.23
      Port: 3306
      DBName: MyDatabase
      MasterUsername: !Ref DbUserName
      MasterUserPassword: !Ref DbUserPassword
      # backup and maintenance parameters
      BackupRetentionPeriod: 2
      PreferredBackupWindow: 19:00-20:00
      PreferredMaintenanceWindow: sat:20:00-sat:21:00
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      Tags:
        - Key: Name
          Value: cfn-db
  rdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Managed by CloudFormation
      SubnetIds:
        - !Ref cfnPrivateSubnet1a
        - !Ref cfnPrivateSubnet1c
      Tags:
        - Key: Name
          Value: cfn-db-subnet
  rdsDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Managed by CloudFormation
      Family: mysql5.7
      Tags:
        - Key: Name
          Value: db-pg
################################
# ALB
################################
  cfnInternetALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: web-alb
      Scheme: internet-facing
      SecurityGroups:
        - !Ref cfnWebSecurityGroup
      Subnets:
        - !Ref cfnPublicSubnet1a
        - !Ref cfnPublicSubnet1c
      Tags:
        - Key: Name
          Value: web-alb
  cfnTargetGroup: 
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties: 
      Name: web-alb-tg
      Port: 80
      Protocol: HTTP
      VpcId: !Ref cfnVPC
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckProtocol: HTTP
      HealthCheckPath: "/"
      HealthCheckPort: "traffic-port"
      HealthCheckIntervalSeconds: 10
      Matcher: 
        HttpCode: 200
      Tags: 
        - Key: Name
          Value: web-alb-tg
      Targets: 
        - Id: !Ref cfnWeb1
          Port: 80
  cfnALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref cfnInternetALB 
      DefaultActions:
        - TargetGroupArn: !Ref cfnTargetGroup
          Type: forward
      Port: 80
      Protocol: HTTP